name: "Windows"

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: clone-repository
        uses: actions/checkout@v3
      - name: build
        run: cmd /c ".github\scripts\windows-build.bat"
      - name: upload-dist
        if: true
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/Microsoft.Data.SqlClient.SNI.dll
            dist/wdb_schema.exe
          retention-days: 1